### ISSUE TITLE
Where are binaries!?

### ISSUE THREAD

**Issue by SammieLJ** [turtlecoin/one-click-miner#1]
Title say it all. Where are binaries!? I only see source code in this repository. wtf

**Comment by brandonlehmann** [comment]
Did you try cloning the repo and building it yourself?

**Comment by SoreGums** [comment]
looks like it is a work in progress, so no binaries yet ;)

**Comment by encryptedunicorn** [comment]
I'll release a new version as soon as the code is ready, it's close and widely usable, but there are still some points to be fixed on my list.
Please also only use the Issues here if you want to tell me about a bug you encounter or a suggestion you want to make.
I'll extend the README with some build instructions and hopefully manage to release a version very soon when I can be online more often again.
If you need anything specific, please tag me on the official TRTL Network Discord server as I get notifications there.
Thanks!
